
export const  Actiontype:any={
  FORM_DATA: "FORM_DATA",
  SET_ACTION:"SET_ACTION",
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCESS: "FETCH_USER_SUCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  LOGOUT: "LOGOUT",
};


